"""

NEXUS Analytics Studio

Advanced AI Analyst v1.3



Evidence-first deterministic analyst layer.

Uses full-dataset ai_context generated by ai_context_service.py.

Falls back to the existing dashboard and preview structures when needed.

"""



from __future__ import annotations



import math

import re

from typing import Any, Dict, List, Optional, Tuple





def _num(value: Any) -> Optional[float]:

    try:

        if value is None or isinstance(value, bool):

            return None

        number = float(value)

        return number if math.isfinite(number) else None

    except (TypeError, ValueError):

        return None





def _norm(value: Any) -> str:

    return re.sub(r"[^a-z0-9]+", " ", str(value).lower()).strip()





def _fmt(value: Any) -> str:

    number = _num(value)

    if number is None:

        return str(value)

    if float(number).is_integer():

        return f"{int(number):,}"

    return f"{number:,.2f}"





def _compact(value: Any) -> str:

    number = _num(value)

    if number is None:

        return str(value)

    absolute = abs(number)

    if absolute >= 1_000_000_000:

        return f"{number / 1_000_000_000:.2f}B"

    if absolute >= 1_000_000:

        return f"{number / 1_000_000:.2f}M"

    if absolute >= 1_000:

        return f"{number / 1_000:.2f}K"

    return _fmt(number)





def _money(value: Any) -> str:

    number = _num(value)

    if number is None:

        return "N/A"

    return f"{number:,.2f}"





def _pct(value: Any) -> str:

    number = _num(value)

    return "N/A" if number is None else f"{number:.2f}%"





def _pretty(name: Any) -> str:

    text = str(name).replace("_", " ").strip()

    return re.sub(r"\s+", " ", text).title()





def _question_type(question: str) -> str:

    q = _norm(question)



    if any(x in q for x in ["recommend", "recommendation", "action", "what should", "next step"]):

        return "recommendation"

    if any(x in q for x in ["summary", "summarize", "key finding", "business insight", "top insight", "overview"]):

        return "summary"

    if any(x in q for x in ["missing", "null", "quality", "duplicate", "duplicates", "completeness"]):

        return "quality"

    if any(x in q for x in ["correlation", "correlated", "relationship between metrics"]):

        return "correlation"

    if any(x in q for x in ["anomal", "outlier", "unusual", "abnormal"]):

        return "anomaly"

    if any(x in q for x in ["trend", "over time", "monthly", "weekly", "daily", "growth", "change over time"]):

        return "trend"

    if any(x in q for x in ["compare", "comparison", "versus", " vs ", "difference between"]):

        return "compare"

    if any(x in q for x in ["lowest", "bottom", "smallest", "minimum", "min", "worst"]):

        return "bottom"

    if any(x in q for x in ["highest", "top", "largest", "best", "maximum", "max", "most", "leading"]):

        return "top"

    return "kpi"





METRIC_ALIASES: Dict[str, List[str]] = {

    "revenue": ["revenue", "sales", "turnover", "sales amount", "total sales"],

    "profit": ["profit", "earnings", "net income"],

    "cost": ["cost", "expense", "expenses"],

    "spend": ["spend", "marketing spend", "ad spend", "advertising spend"],

    "roas": ["roas", "return on ad spend"],

    "ctr": ["ctr", "click through rate", "clickthrough rate"],

    "conversion_rate": ["conversion rate", "conversion percentage"],

    "cpa": ["cpa", "cost per acquisition", "cost per conversion"],

    "cpc": ["cpc", "cost per click"],

    "conversions": ["conversions", "conversion count"],

    "clicks": ["clicks", "click"],

    "impressions": ["impressions", "impression"],

    "orders": ["orders", "order count", "transactions"],

    "customers": ["customers", "customer count", "clients"],

    "quantity": ["quantity", "units", "units sold", "volume"],

    "profit_margin": ["profit margin", "margin"],

    "average_order_value": ["average order value", "aov", "average order"],

    "employees": ["employees", "headcount", "workforce"],

    "attrition_rate": ["attrition", "attrition rate", "turnover rate"],

    "average_salary": ["average salary", "salary"],

    "defects": ["defects", "defect count"],

    "defect_rate": ["defect rate"],

    "quality_rate": ["quality rate", "yield", "quality"],

    "downtime": ["downtime"],

    "maintenance_cost": ["maintenance cost"],

    "production_cost": ["production cost"],

    "total_charges": ["total charges", "charges"],

    "readmission_rate": ["readmission", "readmission rate"],

    "mortality_rate": ["mortality", "mortality rate"],

    "fraud": ["fraud", "fraud amount", "fraud count"],

    "risk": ["risk", "risk score"],

}





MODULE_METRIC_PRIORITIES: Dict[str, List[str]] = {

    "marketing": ["roas", "revenue", "conversions", "conversion_rate", "ctr", "spend"],

    "sales": ["revenue", "profit", "orders", "quantity"],

    "ecommerce": ["revenue", "profit", "orders", "customers", "quantity"],

    "financial": ["profit", "revenue", "profit_margin", "cost"],

    "customer": ["customers", "revenue", "average_order_value"],

    "hr": ["employees", "attrition_rate", "average_salary"],

    "manufacturing": ["quality_rate", "defect_rate", "defects", "downtime", "production_cost"],

    "operations": ["downtime", "cost", "revenue"],

    "supply chain": ["cost", "quantity", "revenue"],

    "product": ["revenue", "profit", "quantity"],

    "fraud": ["fraud", "risk", "revenue"],

    "healthcare": ["readmission_rate", "mortality_rate", "total_charges"],

}





def _metric_aliases(metric: str) -> List[str]:

    return METRIC_ALIASES.get(metric, [metric.replace("_", " ")])





def _match_name(names: List[str], aliases: List[str]) -> Optional[str]:

    normalized = {name: _norm(name) for name in names}

    wanted = [_norm(alias) for alias in aliases if alias]



    for alias in wanted:

        for original, candidate in normalized.items():

            if candidate == alias:

                return original



    for alias in wanted:

        for original, candidate in normalized.items():

            if alias and (alias in candidate or candidate in alias):

                return original



    return None





def _explicit_metric(question: str) -> Optional[str]:
    """Return a canonical metric only when the user explicitly requested it."""
    q = _norm(question)
    matches: List[Tuple[int, str]] = []
    for canonical, aliases in METRIC_ALIASES.items():
        for alias in aliases + [canonical.replace("_", " ")]:
            normalized = _norm(alias)
            if normalized and normalized in q:
                matches.append((len(normalized), canonical))
    if not matches:
        return None
    matches.sort(reverse=True)
    return matches[0][1]


def _metric_unavailable_message(metric: str) -> str:
    formulas = {
        "roas": ("Revenue", "Spend", "Revenue ÷ Spend"),
        "ctr": ("Clicks", "Impressions", "Clicks ÷ Impressions × 100"),
        "conversion_rate": ("Conversions", "Clicks", "Conversions ÷ Clicks × 100"),
        "cpa": ("Spend", "Conversions", "Spend ÷ Conversions"),
        "cpc": ("Spend", "Clicks", "Spend ÷ Clicks"),
        "profit_margin": ("Profit", "Revenue", "Profit ÷ Revenue × 100"),
        "average_order_value": ("Revenue", "Orders", "Revenue ÷ Orders"),
    }
    if metric in formulas:
        left, right, formula = formulas[metric]
        return (
            f"**{_pretty(metric)} cannot be calculated from this dataset.** "
            f"NEXUS could not find the required **{left}** and **{right}** fields "
            f"needed for **{formula}**."
        )
    return (
        f"**{_pretty(metric)} is not available in this dataset.** "
        "NEXUS will not substitute an unrelated numeric field for an explicitly requested metric."
    )


def _requested_metric(question: str, context: Dict[str, Any], module: str = "") -> Tuple[Optional[str], str]:
    derived = context.get("derived_metrics") or {}
    numeric = context.get("numeric_statistics") or {}

    explicit = _explicit_metric(question)
    if explicit:
        if explicit in derived:
            return explicit, "derived"
        match = _match_name(list(numeric.keys()), _metric_aliases(explicit) + [explicit])
        if match:
            return match, "numeric"
        return explicit, "unavailable"

    module_norm = _norm(module)
    for module_key, priorities in MODULE_METRIC_PRIORITIES.items():
        if module_key in module_norm:
            for canonical in priorities:
                if canonical in derived:
                    return canonical, "derived"
                match = _match_name(list(numeric.keys()), _metric_aliases(canonical) + [canonical])
                if match:
                    return match, "numeric"

    if numeric:
        return next(iter(numeric)), "numeric"
    return None, ""

def _requested_dimension(question: str, context: Dict[str, Any]) -> Optional[str]:

    groups = context.get("group_performance") or {}

    names = list(groups.keys())

    q = _norm(question)



    for name in names:

        normalized = _norm(name)

        if normalized and normalized in q:

            return name



    aliases = {

        "channel": ["channel", "source", "medium"],

        "campaign": ["campaign"],

        "region": ["region", "state", "country", "territory", "location"],

        "product": ["product", "item", "sku"],

        "category": ["category", "segment", "type"],

        "department": ["department", "team"],

        "customer": ["customer", "client"],

    }



    for _, words in aliases.items():

        if any(word in q for word in words):

            match = _match_name(names, words)

            if match:

                return match



    return names[0] if names else None





def _numeric_metric_name(context: Dict[str, Any], canonical: str) -> Optional[str]:

    numeric = context.get("numeric_statistics") or {}

    return _match_name(list(numeric.keys()), _metric_aliases(canonical) + [canonical])





def _group_rows(context: Dict[str, Any], dimension: str, metric: str) -> List[Dict[str, Any]]:

    groups = context.get("group_performance") or {}

    dimension_data = groups.get(dimension) or {}



    if metric in dimension_data:

        return dimension_data.get(metric) or []



    match = _match_name(list(dimension_data.keys()), _metric_aliases(metric) + [metric])

    return dimension_data.get(match, []) if match else []





def _derived_group_rows(context: Dict[str, Any], dimension: str, metric: str) -> List[Dict[str, Any]]:

    if metric not in {"roas", "ctr", "conversion_rate", "cpa", "cpc"}:

        return []



    formula_map = {

        "roas": ("revenue", "spend", False),

        "ctr": ("clicks", "impressions", True),

        "conversion_rate": ("conversions", "clicks", True),

        "cpa": ("spend", "conversions", False),

        "cpc": ("spend", "clicks", False),

    }

    numerator_name, denominator_name, percent = formula_map[metric]



    numerator = _numeric_metric_name(context, numerator_name)

    denominator = _numeric_metric_name(context, denominator_name)

    if not numerator or not denominator:

        return []



    num_rows = _group_rows(context, dimension, numerator)

    den_rows = _group_rows(context, dimension, denominator)

    if not num_rows or not den_rows:

        return []



    num_map = {str(row.get("value")): _num(row.get("metric_value")) for row in num_rows}

    den_map = {str(row.get("value")): _num(row.get("metric_value")) for row in den_rows}



    rows: List[Dict[str, Any]] = []

    for label, numerator_value in num_map.items():

        denominator_value = den_map.get(label)

        if numerator_value is None or denominator_value in (None, 0):

            continue

        value = numerator_value / denominator_value

        if percent:

            value *= 100

        rows.append({"value": label, "metric_value": value})



    return rows





def _format_metric(metric: str, value: Any) -> str:

    key = _norm(metric)

    if key in {"ctr", "conversion rate", "attrition rate", "defect rate", "quality rate", "profit margin"} or "percent" in key:

        return _pct(value)

    if key == "roas":

        number = _num(value)

        return "N/A" if number is None else f"{number:.2f}x"

    if key in {"cpa", "cpc"} or any(token in key for token in ["revenue", "profit", "cost", "spend", "salary", "charge", "sales amount"]):

        return _money(value)

    return _compact(value)





def _derived_kpi(context: Dict[str, Any], question: str) -> Optional[Tuple[str, Dict[str, Any]]]:

    derived = context.get("derived_metrics") or {}

    q = _norm(question)

    for key, payload in derived.items():

        aliases = _metric_aliases(key) + [key]

        if any(_norm(alias) in q for alias in aliases):

            return key, payload if isinstance(payload, dict) else {"value": payload}

    return None





def _dashboard_kpi(dashboard: Dict[str, Any], question: str) -> Optional[Tuple[str, Any]]:

    kpis = dashboard.get("kpis") or {}

    if isinstance(kpis, list):

        normalized: Dict[str, Any] = {}

        for item in kpis:

            if not isinstance(item, dict):

                continue

            key = item.get("key") or item.get("name") or item.get("label")

            value = item.get("value")

            if key is not None:

                normalized[str(key)] = value

        kpis = normalized

    if not isinstance(kpis, dict):

        return None



    q = _norm(question)

    for key, value in kpis.items():

        if _norm(key) in q:

            return str(key), value



    for canonical, aliases in METRIC_ALIASES.items():

        if any(_norm(alias) in q for alias in aliases):

            match = _match_name(list(kpis.keys()), aliases + [canonical])

            if match:

                return match, kpis[match]

    return None





def _answer_kpi(question: str, context: Dict[str, Any], dashboard: Dict[str, Any]) -> Tuple[str, List[Dict[str, Any]], Optional[str]]:

    derived = _derived_kpi(context, question)

    if derived:

        key, payload = derived

        value = payload.get("value")

        formula = payload.get("formula")

        answer = f"**{_pretty(key)}: {_format_metric(key, value)}**"

        if formula:

            answer += f"\n\nCalculated from the full dataset using **{formula}**."

        return answer, [{"source": "ai_context.derived_metrics", "field": key, "value": value, "formula": formula}], "kpi"



    metric, source = _requested_metric(question, context)

    if metric and source == "unavailable":
        return _metric_unavailable_message(metric), [{"source": "ai_context", "metric": metric, "available": False}], None

    numeric = context.get("numeric_statistics") or {}

    if metric and source == "numeric" and metric in numeric:

        stats = numeric[metric]

        q = _norm(question)

        if "average" in q or "mean" in q:

            field, value = "mean", stats.get("mean")

        elif "median" in q:

            field, value = "median", stats.get("median")

        elif "minimum" in q or "lowest" in q or " min " in f" {q} ":

            field, value = "min", stats.get("min")

        elif "maximum" in q or "highest" in q or " max " in f" {q} ":

            field, value = "max", stats.get("max")

        else:

            field, value = "sum", stats.get("sum")

        return (

            f"**{_pretty(metric)} {field}: {_format_metric(metric, value)}**",

            [{"source": "ai_context.numeric_statistics", "field": metric, "statistic": field, "value": value}],

            "kpi",

        )



    dashboard_match = _dashboard_kpi(dashboard, question)

    if dashboard_match:

        key, value = dashboard_match

        return (

            f"**{_pretty(key)}: {_format_metric(key, value)}**",

            [{"source": "dashboard.kpis", "field": key, "value": value}],

            "kpi",

        )



    return (

        "I could not identify the requested metric from the available full-dataset statistics.",

        [],

        None,

    )





def _answer_ranking(question: str, context: Dict[str, Any], top: bool) -> Tuple[str, List[Dict[str, Any]], Optional[str]]:

    dimension = _requested_dimension(question, context)

    metric, source = _requested_metric(question, context)

    if not dimension or not metric:

        return "I could not identify both a ranking dimension and performance metric.", [], None



    
    if source == "unavailable":
        return _metric_unavailable_message(metric), [{"source": "ai_context", "metric": metric, "available": False}], None

    rows = _derived_group_rows(context, dimension, metric) if source == "derived" else _group_rows(context, dimension, metric)

    if not rows:

        return f"I could not calculate {_pretty(metric)} by {_pretty(dimension)} from the available full-dataset aggregates.", [], None



    usable = []

    for row in rows:

        value = _num(row.get("metric_value"))

        label = row.get("value")

        if label is not None and value is not None:

            usable.append((str(label), value))



    if not usable:

        return "The ranking series exists, but it does not contain usable numeric values.", [], None



    usable.sort(key=lambda item: item[1], reverse=top)

    winner = usable[0]

    direction = "highest" if top else "lowest"



    answer = (

        f"The **{direction} {_pretty(dimension)} by {_pretty(metric)}** is "

        f"**{winner[0]}** with **{_format_metric(metric, winner[1])}**."

    )

    evidence = [{

        "source": "ai_context.group_performance",

        "dimension": dimension,

        "metric": metric,

        "ranking": [{"name": name, "value": value} for name, value in usable[:5]],

    }]

    return answer, evidence, "ranking"





def _answer_quality(context: Dict[str, Any], dashboard: Dict[str, Any]) -> Tuple[str, List[Dict[str, Any]], Optional[str]]:

    quality = context.get("quality") or {}

    if quality:

        answer = (

            f"Full-dataset quality: **{_pct(quality.get('completeness_percent'))} completeness**, "

            f"**{_fmt(quality.get('missing_cells', 0))} missing cells**, and "

            f"**{_fmt(quality.get('duplicate_rows', 0))} duplicate rows** "

            f"across **{_fmt(quality.get('rows', 0))} rows × {_fmt(quality.get('columns', 0))} columns**."

        )

        return answer, [{"source": "ai_context.quality", "value": quality}], "quality"



    legacy = dashboard.get("quality") or {}

    if legacy:

        return "Data-quality evidence is available from the dashboard analysis.", [{"source": "dashboard.quality", "value": legacy}], "quality"

    return "No data-quality metrics are available.", [], None





def _answer_trend(question: str, context: Dict[str, Any]) -> Tuple[str, List[Dict[str, Any]], Optional[str]]:

    trends = context.get("trends") or {}

    metrics = trends.get("metrics") or {}

    if not metrics:

        return "No full-dataset time-series trend is available for this dataset.", [], None



    requested, requested_source = _requested_metric(question, context)

    if requested and requested_source == "unavailable":
        return _metric_unavailable_message(requested), [{"source": "ai_context", "metric": requested, "available": False}], None

    metric = _match_name(list(metrics.keys()), _metric_aliases(requested or "") + ([requested] if requested else []))

    if not metric:

        q = _norm(question)

        metric = next((name for name in metrics if _norm(name) in q), None) or next(iter(metrics))



    payload = metrics.get(metric) or {}

    points = payload.get("points") or []

    if not points:

        return "A trend metric was identified, but no usable trend points are available.", [], None



    first = _num(payload.get("first"))

    latest = _num(payload.get("latest"))

    change_pct = _num(payload.get("change_percent"))

    first_period = points[0].get("period")

    latest_period = points[-1].get("period")



    if first is None or latest is None:

        return f"A {_pretty(metric)} trend is available, but the endpoint values are not numeric.", [{"source": "ai_context.trends", "metric": metric, "points": points}], "trend"



    difference = latest - first

    direction = "increased" if difference > 0 else "decreased" if difference < 0 else "was unchanged"

    pct_text = f" ({abs(change_pct):.2f}%)" if change_pct is not None else ""



    answer = (

        f"**{_pretty(metric)} {direction}** from **{_format_metric(metric, first)}** in "

        f"**{first_period}** to **{_format_metric(metric, latest)}** in **{latest_period}**{pct_text}."

    )

    return answer, [{"source": "ai_context.trends", "metric": metric, "points": points}], "trend"





def _answer_correlation(context: Dict[str, Any]) -> Tuple[str, List[Dict[str, Any]], Optional[str]]:

    correlations = context.get("correlations") or []

    usable = [item for item in correlations if _num(item.get("correlation")) is not None]

    if not usable:

        return "No usable numeric correlation pairs are available in the full-dataset context.", [], None



    usable.sort(key=lambda item: abs(float(item["correlation"])), reverse=True)

    top = usable[:5]

    lines = []

    for item in top:

        value = float(item["correlation"])

        direction = "positive" if value > 0 else "negative"

        lines.append(

            f"- **{item.get('column_a')} ↔ {item.get('column_b')}**: {value:.3f} ({direction})"

        )

    answer = "Strongest available numeric relationships:\n\n" + "\n".join(lines)

    return answer, [{"source": "ai_context.correlations", "value": top}], "correlation"





def _answer_anomaly(context: Dict[str, Any]) -> Tuple[str, List[Dict[str, Any]], Optional[str]]:

    anomalies = context.get("anomalies") or []

    if not anomalies:

        return "No IQR-based numeric outliers were detected in the full-dataset context.", [], "anomaly"



    total = sum(int(item.get("count") or 0) for item in anomalies)

    lines = []

    for item in anomalies[:5]:

        lines.append(

            f"- **{item.get('column')}**: {_fmt(item.get('count', 0))} outliers "

            f"(expected range {_fmt(item.get('lower_bound'))} to {_fmt(item.get('upper_bound'))})"

        )

    answer = f"The full dataset contains **{_fmt(total)} detected numeric outlier occurrences** across the analyzed metrics.\n\n" + "\n".join(lines)

    return answer, [{"source": "ai_context.anomalies", "value": anomalies[:10]}], "anomaly"





def _category_candidates(context: Dict[str, Any], dimension: str) -> List[str]:
    """Return known categorical values for a dimension from full-dataset context."""
    categories = context.get("categorical_statistics") or {}
    payload = categories.get(dimension) or {}
    values: List[str] = []
    for item in payload.get("top_values", []) or []:
        if not isinstance(item, dict) or item.get("value") is None:
            continue
        label = str(item.get("value"))
        if label not in values:
            values.append(label)

    # group_performance can contain values beyond categorical top_values.
    dimension_data = (context.get("group_performance") or {}).get(dimension) or {}
    for rows in dimension_data.values():
        if not isinstance(rows, list):
            continue
        for row in rows:
            if isinstance(row, dict) and row.get("value") is not None:
                label = str(row.get("value"))
                if label not in values:
                    values.append(label)
    return values


def _values_mentioned(question: str, candidates: List[str]) -> List[str]:
    """Find categorical values explicitly mentioned in the question."""
    q = _norm(question)
    matches: List[Tuple[int, int, str]] = []
    for candidate in candidates:
        normalized = _norm(candidate)
        if not normalized:
            continue
        # Boundary-aware matching prevents short labels from matching inside words.
        match = re.search(rf"(?<![a-z0-9]){re.escape(normalized)}(?![a-z0-9])", q)
        if match:
            matches.append((match.start(), -len(normalized), candidate))
    matches.sort()
    values: List[str] = []
    for _, _, candidate in matches:
        if candidate not in values:
            values.append(candidate)
    return values


def _detect_compare_dimension_and_values(
    question: str,
    context: Dict[str, Any],
) -> Tuple[Optional[str], List[str]]:
    """
    Resolve the comparison dimension from the values named by the user.

    Example: "Compare Google vs Meta" resolves Channel when Google and Meta are
    Channel values, even though the word "channel" is absent from the question.
    """
    groups = context.get("group_performance") or {}
    categories = context.get("categorical_statistics") or {}
    dimensions: List[str] = []
    for name in list(groups.keys()) + list(categories.keys()):
        if name not in dimensions:
            dimensions.append(name)

    explicit_dimension = _requested_dimension(question, context)
    scored: List[Tuple[int, int, str, List[str]]] = []
    for index, dimension in enumerate(dimensions):
        values = _values_mentioned(question, _category_candidates(context, dimension))
        if values:
            bonus = 1 if explicit_dimension == dimension else 0
            scored.append((len(values), bonus, dimension, values))

    if scored:
        # Prefer the dimension containing the most explicitly named values.
        scored.sort(key=lambda item: (item[0], item[1], -dimensions.index(item[2])), reverse=True)
        best = scored[0]
        if best[0] >= 2:
            return best[2], best[3][:2]

    if explicit_dimension:
        return explicit_dimension, _values_mentioned(
            question, _category_candidates(context, explicit_dimension)
        )[:2]

    return None, []


def _comparison_metric_candidates(
    question: str,
    context: Dict[str, Any],
    dimension: str,
    module: str = "",
) -> List[Tuple[str, str]]:
    """Choose explicit or business-relevant metrics that can be compared by dimension."""
    explicit = _explicit_metric(question)
    if explicit:
        derived = context.get("derived_metrics") or {}
        if explicit in derived and _derived_group_rows(context, dimension, explicit):
            return [(explicit, "derived")]
        numeric_name = _numeric_metric_name(context, explicit)
        if numeric_name and _group_rows(context, dimension, numeric_name):
            return [(numeric_name, "numeric")]
        return [(explicit, "unavailable")]

    module_norm = _norm(module)
    priorities: List[str] = []
    for module_key, values in MODULE_METRIC_PRIORITIES.items():
        if module_key in module_norm:
            priorities = values
            break

    # Marketing comparisons are most useful as a small business-performance scorecard.
    if "marketing" in module_norm:
        priorities = [
            "revenue", "spend", "roas", "conversions",
            "conversion_rate", "ctr", "clicks", "impressions",
        ]

    selected: List[Tuple[str, str]] = []
    seen: set[str] = set()
    for canonical in priorities:
        if canonical in seen:
            continue
        if _derived_group_rows(context, dimension, canonical):
            selected.append((canonical, "derived"))
            seen.add(canonical)
        else:
            numeric_name = _numeric_metric_name(context, canonical)
            if numeric_name and _group_rows(context, dimension, numeric_name):
                selected.append((numeric_name, "numeric"))
                seen.add(canonical)
        if len(selected) >= 6:
            break

    if not selected:
        dimension_data = (context.get("group_performance") or {}).get(dimension) or {}
        for metric in dimension_data:
            if _group_rows(context, dimension, metric):
                selected.append((metric, "numeric"))
            if len(selected) >= 4:
                break
    return selected


def _comparison_value(
    context: Dict[str, Any],
    dimension: str,
    metric: str,
    source: str,
    label: str,
) -> Optional[float]:
    rows = (
        _derived_group_rows(context, dimension, metric)
        if source == "derived"
        else _group_rows(context, dimension, metric)
    )
    wanted = _norm(label)
    for row in rows:
        if _norm(row.get("value")) == wanted:
            return _num(row.get("metric_value"))
    return None


def _answer_compare(
    question: str,
    context: Dict[str, Any],
    module: str = "",
) -> Tuple[str, List[Dict[str, Any]], Optional[str]]:
    dimension, values = _detect_compare_dimension_and_values(question, context)

    if not dimension:
        return (
            "I could not determine which dataset dimension the requested values belong to.",
            [],
            None,
        )

    metrics = _comparison_metric_candidates(question, context, dimension, module)
    if metrics and metrics[0][1] == "unavailable":
        return (
            _metric_unavailable_message(metrics[0][0]),
            [{"source": "ai_context", "metric": metrics[0][0], "available": False}],
            None,
        )

    # If two values were not named, retain the previous behavior and use the
    # strongest two groups on the first available comparison metric.
    if len(values) < 2 and metrics:
        metric, source = metrics[0]
        rows = (
            _derived_group_rows(context, dimension, metric)
            if source == "derived"
            else _group_rows(context, dimension, metric)
        )
        usable = [
            (str(row.get("value")), _num(row.get("metric_value")))
            for row in rows
            if row.get("value") is not None
        ]
        usable = [(name, value) for name, value in usable if value is not None]
        usable.sort(key=lambda item: item[1], reverse=True)
        values = [item[0] for item in usable[:2]]

    if len(values) < 2:
        return (
            f"I found the {_pretty(dimension)} dimension, but could not identify two values to compare.",
            [],
            None,
        )

    a_name, b_name = values[0], values[1]
    evidence_metrics: Dict[str, Dict[str, Any]] = {}
    lines: List[str] = []
    explicit_metric = _explicit_metric(question)

    for metric, source in metrics:
        a = _comparison_value(context, dimension, metric, source, a_name)
        b = _comparison_value(context, dimension, metric, source, b_name)
        if a is None or b is None:
            continue
        evidence_metrics[metric] = {a_name: a, b_name: b, "source_type": source}
        difference = a - b
        if difference > 0:
            leader = a_name
        elif difference < 0:
            leader = b_name
        else:
            leader = "Tie"
        lines.append(
            f"- **{_pretty(metric)}:** {a_name} = **{_format_metric(metric, a)}**; "
            f"{b_name} = **{_format_metric(metric, b)}**"
            + (f" — **{leader}** is higher." if leader != "Tie" else " — **Tie**.")
        )

    if not lines:
        return (
            f"I found **{a_name}** and **{b_name}** under **{_pretty(dimension)}**, "
            "but no shared numeric comparison metric was available.",
            [],
            None,
        )

    if explicit_metric and len(lines) == 1:
        metric = next(iter(evidence_metrics))
        values_map = evidence_metrics[metric]
        a = values_map[a_name]
        b = values_map[b_name]
        difference = a - b
        if difference > 0:
            conclusion = f"**{a_name}** is higher by **{_format_metric(metric, abs(difference))}**."
        elif difference < 0:
            conclusion = f"**{b_name}** is higher by **{_format_metric(metric, abs(difference))}**."
        else:
            conclusion = "Both groups have the same value."
        answer = (
            f"Comparing **{a_name}** vs **{b_name}** on **{_pretty(metric)}**: "
            f"{a_name} = **{_format_metric(metric, a)}**, "
            f"{b_name} = **{_format_metric(metric, b)}**. {conclusion}"
        )
    else:
        answer = (
            f"**{a_name} vs {b_name} — {_pretty(dimension)} comparison**\n\n"
            + "\n".join(lines)
        )

    evidence = [{
        "source": "ai_context.group_performance",
        "dimension": dimension,
        "values": [a_name, b_name],
        "metrics": evidence_metrics,
    }]
    return answer, evidence, "comparison"



def _summary_insights(context: Dict[str, Any], module: str) -> List[str]:

    insights: List[str] = []

    quality = context.get("quality") or {}

    derived = context.get("derived_metrics") or {}

    numeric = context.get("numeric_statistics") or {}

    groups = context.get("group_performance") or {}

    trends = context.get("trends") or {}

    anomalies = context.get("anomalies") or []



    if quality:

        insights.append(

            f"Data quality is {_pct(quality.get('completeness_percent'))} complete with "

            f"{_fmt(quality.get('missing_cells', 0))} missing cells and "

            f"{_fmt(quality.get('duplicate_rows', 0))} duplicate rows."

        )



    priorities = []

    module_norm = _norm(module)

    for key, values in MODULE_METRIC_PRIORITIES.items():

        if key in module_norm:

            priorities = values

            break



    for metric in priorities:

        if metric in derived:

            value = derived[metric].get("value") if isinstance(derived[metric], dict) else derived[metric]

            insights.append(f"{_pretty(metric)} is {_format_metric(metric, value)}.")

            if len(insights) >= 3:

                break



    if len(insights) < 3:

        for metric, stats in numeric.items():

            value = stats.get("sum")

            if value is not None:

                insights.append(

                    f"{_pretty(metric)} totals {_format_metric(metric, value)} "

                    f"with an average of {_format_metric(metric, stats.get('mean'))}."

                )

            if len(insights) >= 3:

                break



    # Add one useful ranking.

    if groups:

        dimension = next(iter(groups))

        metric, source = _requested_metric("", context, module)

        if metric:

            rows = _derived_group_rows(context, dimension, metric) if source == "derived" else _group_rows(context, dimension, metric)

            usable = [(str(row.get("value")), _num(row.get("metric_value"))) for row in rows]

            usable = [(name, value) for name, value in usable if value is not None]

            if usable:

                winner = max(usable, key=lambda item: item[1])

                insights.append(

                    f"{winner[0]} leads {_pretty(dimension)} performance on {_pretty(metric)} at {_format_metric(metric, winner[1])}."

                )



    metrics = trends.get("metrics") or {}

    if metrics:

        metric = next(iter(metrics))

        change = _num(metrics[metric].get("change_percent"))

        if change is not None:

            direction = "up" if change > 0 else "down" if change < 0 else "flat"

            insights.append(f"{_pretty(metric)} trend is {direction} {abs(change):.2f}% from the first to latest available period.")



    if anomalies:

        count = sum(int(item.get("count") or 0) for item in anomalies)

        insights.append(f"IQR analysis detected {_fmt(count)} numeric outlier occurrences.")



    return insights[:5]





def _answer_summary(context: Dict[str, Any], module: str) -> Tuple[str, List[Dict[str, Any]], Optional[str]]:

    insights = _summary_insights(context, module)

    if not insights:

        return "The full-dataset context does not contain enough statistical evidence to produce a reliable summary.", [], None

    answer = "Key findings from the full dataset:\n\n" + "\n".join(f"{i + 1}. {text}" for i, text in enumerate(insights))

    return answer, [{"source": "ai_context", "insights": insights}], "summary"





def _answer_recommendations(context: Dict[str, Any], module: str) -> Tuple[str, List[Dict[str, Any]], Optional[str]]:

    insights = _summary_insights(context, module)

    recommendations: List[str] = []

    anomalies = context.get("anomalies") or {}

    quality = context.get("quality") or {}

    groups = context.get("group_performance") or {}



    if quality and (_num(quality.get("missing_percent")) or 0) > 0:

        recommendations.append(

            f"Resolve the {_pct(quality.get('missing_percent'))} missing-cell rate before using the dataset for high-impact decisions."

        )

    if quality and int(quality.get("duplicate_rows") or 0) > 0:

        recommendations.append(

            f"Review and remove the {_fmt(quality.get('duplicate_rows'))} duplicate rows unless they represent valid repeated events."

        )

    if anomalies:

        first = anomalies[0]

        recommendations.append(

            f"Investigate the {_fmt(first.get('count', 0))} outliers in {_pretty(first.get('column'))}; verify whether they are valid extreme cases or data/process issues."

        )



    metric, source = _requested_metric("", context, module)

    if groups and metric:

        dimension = next(iter(groups))

        rows = _derived_group_rows(context, dimension, metric) if source == "derived" else _group_rows(context, dimension, metric)

        usable = [(str(row.get("value")), _num(row.get("metric_value"))) for row in rows]

        usable = [(name, value) for name, value in usable if value is not None]

        if len(usable) >= 2:

            best = max(usable, key=lambda item: item[1])

            worst = min(usable, key=lambda item: item[1])

            recommendations.append(

                f"Study what drives {_pretty(dimension)} **{best[0]}** ({_format_metric(metric, best[1])}) and apply transferable practices to **{worst[0]}** ({_format_metric(metric, worst[1])})."

            )



    trends = context.get("trends") or {}

    trend_metrics = trends.get("metrics") or {}

    if trend_metrics:

        name = next(iter(trend_metrics))

        change = _num(trend_metrics[name].get("change_percent"))

        if change is not None and change < 0:

            recommendations.append(

                f"Prioritize root-cause analysis for the {abs(change):.2f}% decline in {_pretty(name)} across the available time range."

            )



    if not recommendations:

        recommendations.append("Use the strongest-performing group as a benchmark and validate its drivers before reallocating resources.")

        recommendations.append("Review the lowest-performing group against the dataset's main numeric KPIs to identify the largest improvement opportunity.")

        recommendations.append("Validate major decisions against operational context; these recommendations are based on statistical patterns in the uploaded data.")



    answer = "Recommended actions based on the available evidence:\n\n" + "\n".join(

        f"{i + 1}. {item}" for i, item in enumerate(recommendations[:5])

    )

    return answer, [{"source": "ai_context", "supporting_insights": insights, "recommendations": recommendations[:5]}], "recommendation"





def _legacy_ranking(dashboard: Dict[str, Any], question: str) -> Optional[str]:

    q = _norm(question)

    for key, label in [

        ("category_performance", "category"),

        ("region_performance", "region"),

        ("product_performance", "product"),

        ("channel_performance", "channel"),

    ]:

        rows = dashboard.get(key) or []

        if not rows or not isinstance(rows, list) or not isinstance(rows[0], dict):

            continue

        metric = "profit" if "profit" in q and "profit" in rows[0] else None

        if not metric:

            metric = "sales" if "sales" in rows[0] else ("revenue" if "revenue" in rows[0] else None)

        if not metric:

            continue

        usable = []

        for row in rows:

            name = row.get(label, row.get(label.title(), row.get("name")))

            value = _num(row.get(metric))

            if name is not None and value is not None:

                usable.append((name, value))

        if usable:

            reverse = not any(x in q for x in ["lowest", "bottom", "smallest", "minimum", "min", "worst"])

            item = sorted(usable, key=lambda x: x[1], reverse=reverse)[0]

            direction = "highest" if reverse else "lowest"

            return f"The {direction} {label} by {metric} is **{item[0]}** with **{_format_metric(metric, item[1])}**."

    return None







def _conversation_messages(conversation: Optional[List[Dict[str, Any]]]) -> List[Dict[str, str]]:
    """Normalize and bound client-provided conversation history."""
    clean: List[Dict[str, str]] = []
    for item in (conversation or [])[-8:]:
        if not isinstance(item, dict):
            continue
        role = str(item.get("role") or "").strip().lower()
        content = str(item.get("content") or "").strip()
        if role in {"user", "assistant"} and content:
            clean.append({"role": role, "content": content[:4000]})
    return clean


def _conversation_state(
    conversation: Optional[List[Dict[str, Any]]],
    context: Dict[str, Any],
) -> Dict[str, Any]:
    """Recover recent metric, dimension and categorical values deterministically."""
    messages = _conversation_messages(conversation)
    state: Dict[str, Any] = {"metric": None, "dimension": None, "values": []}
    dimensions: List[str] = []
    for name in list((context.get("group_performance") or {}).keys()) + list((context.get("categorical_statistics") or {}).keys()):
        if name not in dimensions:
            dimensions.append(name)

    # Walk newest to oldest so the closest conversational reference wins.
    for item in reversed(messages):
        content = item["content"]
        if state["metric"] is None:
            metric = _explicit_metric(content)
            if metric:
                state["metric"] = metric
        if state["dimension"] is None:
            q = _norm(content)
            for dimension in dimensions:
                if _norm(dimension) and _norm(dimension) in q:
                    state["dimension"] = dimension
                    break
        for dimension in dimensions:
            found = _values_mentioned(content, _category_candidates(context, dimension))
            if found:
                if state["dimension"] is None:
                    state["dimension"] = dimension
                for value in found:
                    if value not in state["values"]:
                        state["values"].append(value)
        if state["metric"] and state["dimension"] and state["values"]:
            break
    return state


def _resolve_conversation_question(
    question: str,
    conversation: Optional[List[Dict[str, Any]]],
    context: Dict[str, Any],
) -> Tuple[str, Dict[str, Any]]:
    """Expand short follow-ups into standalone questions for the v1.2 engine."""
    messages = _conversation_messages(conversation)
    if not messages or not isinstance(context, dict):
        return question, {"used": False}

    q = _norm(question)
    state = _conversation_state(messages, context)
    current_metric = _explicit_metric(question)

    current_dimension: Optional[str] = None
    current_values: List[str] = []
    dimensions: List[str] = []
    for name in list((context.get("group_performance") or {}).keys()) + list((context.get("categorical_statistics") or {}).keys()):
        if name not in dimensions:
            dimensions.append(name)
    for dimension in dimensions:
        values = _values_mentioned(question, _category_candidates(context, dimension))
        if values:
            current_dimension = dimension
            current_values = values
            break

    is_compare = any(token in q for token in ["compare", "comparison", "versus", " vs ", "difference between"])
    is_short_followup = (
        len(q.split()) <= 8
        or q.startswith("what about")
        or q.startswith("how about")
        or q.startswith("and ")
        or any(token in f" {q} " for token in [" it ", " that ", " them ", " those ", " one "])
    )
    if not is_short_followup and not is_compare:
        return question, {"used": False}

    metric = current_metric or state.get("metric")
    dimension = current_dimension or state.get("dimension")
    prior_values = list(state.get("values") or [])

    if is_compare:
        values: List[str] = []
        # Pronouns such as "it" refer to the most recent prior entity.
        if any(token in f" {q} " for token in [" it ", " that ", " one "]) and prior_values:
            values.append(prior_values[0])
        for value in current_values:
            if value not in values:
                values.append(value)
        for value in prior_values:
            if value not in values:
                values.append(value)
        if dimension and len(values) >= 2:
            resolved = f"Compare {values[0]} vs {values[1]}"
            if metric:
                resolved += f" on {metric.replace('_', ' ')}"
            resolved += f" by {dimension}"
            return resolved, {"used": True, "metric": metric, "dimension": dimension, "values": values[:2]}

    # "What about Google?" keeps the previous metric. "What about ROAS?"
    # keeps the most recent entity/dimension while changing the metric.
    value = current_values[0] if current_values else (prior_values[0] if current_metric and prior_values else None)
    if value and dimension and metric:
        resolved = f"What is {metric.replace('_', ' ')} for {value} by {dimension}?"
        return resolved, {"used": True, "metric": metric, "dimension": dimension, "values": [value]}

    return question, {"used": False}


def _answer_group_value(
    question: str,
    context: Dict[str, Any],
) -> Optional[Tuple[str, List[Dict[str, Any]], Optional[str]]]:
    """Answer a metric for one explicitly named categorical value."""
    metric = _explicit_metric(question)
    if not metric:
        return None

    dimensions: List[str] = []
    for name in list((context.get("group_performance") or {}).keys()) + list((context.get("categorical_statistics") or {}).keys()):
        if name not in dimensions:
            dimensions.append(name)

    for dimension in dimensions:
        values = _values_mentioned(question, _category_candidates(context, dimension))
        if len(values) != 1:
            continue
        label = values[0]
        if _derived_group_rows(context, dimension, metric):
            source = "derived"
            resolved_metric = metric
        else:
            numeric_name = _numeric_metric_name(context, metric)
            if numeric_name and _group_rows(context, dimension, numeric_name):
                source = "numeric"
                resolved_metric = numeric_name
            else:
                return (
                    _metric_unavailable_message(metric),
                    [{"source": "ai_context", "metric": metric, "available": False}],
                    None,
                )
        value = _comparison_value(context, dimension, resolved_metric, source, label)
        if value is None:
            continue
        answer = (
            f"**{label} {_pretty(resolved_metric)}: {_format_metric(resolved_metric, value)}**\n\n"
            f"Calculated from the full-dataset **{_pretty(dimension)}** aggregates."
        )
        evidence = [{
            "source": "ai_context.group_performance",
            "dimension": dimension,
            "group": label,
            "metric": resolved_metric,
            "value": value,
            "source_type": source,
        }]
        return answer, evidence, "kpi"
    return None


def analyze_question(

    question: str,

    dataset_result: Optional[Dict[str, Any]] = None,

    conversation: Optional[List[Dict[str, Any]]] = None,

) -> Dict[str, Any]:

    result = dataset_result or {}

    context = result.get("ai_context") or {}

    dashboard = result.get("dashboard") or {}

    module = str(result.get("module") or context.get("module") or "")

    original_question = question

    question, conversation_resolution = _resolve_conversation_question(
        question, conversation, context if isinstance(context, dict) else {}
    )

    qtype = _question_type(question)



    answer = ""

    evidence: List[Dict[str, Any]] = []

    chart: Optional[str] = None



    context_available = bool(context.get("available")) if isinstance(context, dict) else False



    if context_available:

        group_answer = _answer_group_value(question, context)

        if group_answer is not None and qtype not in {"compare", "top", "bottom", "summary", "recommendation", "quality", "trend", "correlation", "anomaly"}:

            answer, evidence, chart = group_answer

        elif qtype == "quality":

            answer, evidence, chart = _answer_quality(context, dashboard)

        elif qtype == "trend":

            answer, evidence, chart = _answer_trend(question, context)

        elif qtype == "correlation":

            answer, evidence, chart = _answer_correlation(context)

        elif qtype == "anomaly":

            answer, evidence, chart = _answer_anomaly(context)

        elif qtype == "compare":

            answer, evidence, chart = _answer_compare(question, context, module)

        elif qtype == "top":

            answer, evidence, chart = _answer_ranking(question, context, True)

        elif qtype == "bottom":

            answer, evidence, chart = _answer_ranking(question, context, False)

        elif qtype == "summary":

            answer, evidence, chart = _answer_summary(context, module)

        elif qtype == "recommendation":

            answer, evidence, chart = _answer_recommendations(context, module)

        else:

            answer, evidence, chart = _answer_kpi(question, context, dashboard)



    else:

        # Compatibility with datasets analyzed before ai_context v1.1.

        if qtype == "quality":

            answer, evidence, chart = _answer_quality({}, dashboard)

        elif qtype in {"top", "bottom"}:

            answer = _legacy_ranking(dashboard, question) or (

                "I could not find a ranked category, region, product, or channel series in this analysis."

            )

            chart = "ranking"

        else:

            dashboard_match = _dashboard_kpi(dashboard, question)

            if dashboard_match:

                key, value = dashboard_match

                answer = f"**{_pretty(key)}: {_format_metric(key, value)}**"

                evidence = [{"source": "dashboard.kpis", "field": key, "value": value}]

                chart = "kpi"

            else:

                preview = result.get("preview") or {}

                columns = preview.get("columns") or []

                rows = preview.get("rows") or []

                if "column" in _norm(question) and columns:

                    answer = "The available columns are:\n\n" + ", ".join(f"`{column}`" for column in columns)

                    evidence = [{"source": "preview.columns", "value": columns}]

                elif rows:

                    answer = (

                        f"The dataset preview contains **{len(rows)} rows** and "

                        f"**{len(columns)} columns**. Re-analyze the file with NEXUS v1.1 "

                        "to enable full-dataset AI statistics."

                    )

                    evidence = [{"source": "preview", "rows": len(rows), "columns": len(columns)}]

                else:

                    answer = "No usable analytical context is available for this question."



    return {

        "success": True,

        "answer": answer,

        "question": original_question,

        "resolved_question": question,

        "conversation_resolution": conversation_resolution,

        "intent": qtype,

        "evidence": evidence,

        "suggested_chart": chart,

        "engine": "nexus-ai-analyst-v1.3",

        "context_version": context.get("version") if isinstance(context, dict) else None,

        "full_dataset_context": context_available,

        "dataset": {

            "filename": result.get("filename"),

            "module": result.get("module"),

            "shape": result.get("shape"),

            "columns": result.get("columns"),

        },

    }
